# Gerenciamento de Personganens

### Pega todos os Personagens
GET http://localhost:8888/characters
AncientAuth: {{auth}}

### Pega um personagem específico
GET http://localhost:8888/characters/1
AncientAuth: {{auth}}

### Pega as perguntas relacioadas àquele personagem
GET http://localhost:8888/characters/1/questions
AncientAuth: {{auth}}

### Cria um novo personagem
POST http://localhost:8888/characters
Content-Type: application/json
AncientAuth: {{auth}}

{
  "name": "Adão"
}

### Altera um personagem
PUT http://localhost:8888/characters/2
Content-Type: application/json
AncientAuth: {{auth}}

{
  "name": "Abrão"
}

### Apaga um personagem
DELETE http://localhost:8888/characters/2
AncientAuth: {{auth}}
