# Gerenciamento de Personganens

### Pega todos os Personagens
GET http://localhost:8888/characters
AncientAuth: {{auth}}

### Pega um personagem específico juntamente com as perguntas relacionadas a ele
GET http://localhost:8888/characters/105
AncientAuth: {{auth}}

### Cria um novo personagem
POST http://localhost:8888/characters
Content-Type: application/json
AncientAuth: {{auth}}

{
  "name": "Adaão"
}

### Altera um personagem
PUT http://localhost:8888/characters/105
Content-Type: application/json
AncientAuth: {{auth}}

{
  "name": "Aaadão",
  "questionIds": [1, 2, 3]
}

### Apaga um personagem
DELETE http://localhost:8888/characters/105
AncientAuth: {{auth}}
