# Gerenciamento do Jogo
# Para todos os endpoints informar: /game/{room code}/{gamer id}

### Pega os dados do jogador.
GET http://localhost:8888/game/D6B180/2
Content-Type: application/json
Ancient-Auth: {{auth}}

### Permite o início do jogo
GET http://localhost:8888/game/D6B180/2/allow
Content-Type: application/json
Ancient-Auth: {{auth}}

### Avança a fase
POST http://localhost:8888/game/D6B180/3
Content-Type: application/json
Ancient-Auth: {{auth}}
