GET http://localhost:8888/people
Authorization: Basic YW5jaWVudDo0bkMxM250ITIwMjQ=

###
GET http://localhost:8888/people/1
Authorization: Basic YW5jaWVudDo0bkMxM250ITIwMjQ=

###
POST http://localhost:8888/people
Content-Type: application/json
Authorization: Basic YW5jaWVudDo0bkMxM250ITIwMjQ=

{
  "name": "Adão"
}

###
DELETE http://localhost:8888/people/4
Authorization: Basic YW5jaWVudDo0bkMxM250ITIwMjQ=

###
PUT http://localhost:8888/people/1
Content-Type: application/json
Authorization: Basic YW5jaWVudDo0bkMxM250ITIwMjQ=

{
  "name": "Abraão"
}