GET http://localhost:8888/people
Authorization: Basic c3phZ290OkRTcGlkZXIxOTgx

###
GET http://localhost:8888/people/1
Authorization: Basic c3phZ290OkRTcGlkZXIxOTgx

###
POST http://localhost:8888/people
Content-Type: application/json
Authorization: Basic c3phZ290OkRTcGlkZXIxOTgx

{
  "name": "Adão"
}

###
DELETE http://localhost:8888/people/4
Authorization: Basic c3phZ290OkRTcGlkZXIxOTgx

###
PUT http://localhost:8888/people/1
Content-Type: application/json
Authorization: Basic c3phZ290OkRTcGlkZXIxOTgx

{
  "name": "Abraão"
}