GET http://localhost:8888/people

###
GET http://localhost:8888/people/1

###
POST http://localhost:8888/people
Content-Type: application/json

{
  "name": "Adão"
}

###
DELETE http://localhost:8888/people/4

###
PUT http://localhost:8888/people/1
Content-Type: application/json

{
  "name": "Abraão"
}