GET http://localhost:8888/questions
Authorization: Basic {{auth}}

###
GET http://localhost:8888/questions/1
Authorization: Basic {{auth}}

###
GET http://localhost:8888/questions/1/characters
Authorization: Basic {{auth}}
