# Gerenciamento da Sala e Jogadores da Sala

### Criando a Sala
POST http://localhost:8888/room
Content-Type: application/json
AncientAuth: {{auth}}

{
  "name": "szagot"
}

### Adicionando Jogadores
POST http://localhost:8888/room/D6B180
Content-Type: application/json
AncientAuth: {{auth}}

{
  "name": "daniel"
}

### Sala
GET http://localhost:8888/room/D6B180
Content-Type: application/json
AncientAuth: {{auth}}

### Jogadores da Sala
GET http://localhost:8888/room/D6B180/gamers
Content-Type: application/json
AncientAuth: {{auth}}

### Jogador Fora da Rodada
GET http://localhost:8888/room/D6B180/outOfLoop
Content-Type: application/json
AncientAuth: {{auth}}

### Personagem Secreto
GET http://localhost:8888/room/D6B180/secret
Content-Type: application/json
AncientAuth: {{auth}}

### Deixando a Sala
DELETE http://localhost:8888/room/D6B180
Content-Type: application/json
AncientAuth: {{auth}}

{
  "id": 2
}
