# Gerenciamento da Sala e Jogadores da Sala

### Criando a Sala
POST http://localhost:8888/room
Content-Type: application/json
Ancient-Auth: {{auth}}

{
  "name": "szagot"
}

### Adicionando Jogadores
POST http://localhost:8888/room/D6B180
Content-Type: application/json
Ancient-Auth: {{auth}}

{
  "name": "sara"
}

### Sala
GET http://localhost:8888/room/D6B180
Content-Type: application/json
Ancient-Auth: {{auth}}

### Deixando a Sala
DELETE http://localhost:8888/room/DB8E19
Content-Type: application/json
Ancient-Auth: {{auth}}

{
  "id": 6
}
